name: example
description: A sample command-line application.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  free_dictionary_api_v2:
    path: ../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
