name: free_dictionary_api_v2
description: Package to access the https://dictionaryapi.dev
version: 1.0.3
homepage: https://github.com/tyypgzl/free_dictionary_api_v2
issue_tracker: https://github.com/tyypgzl/free_dictionary_api_v2/issues
topics:
  - api
  - english
  - dictionary

environment:
  sdk: "^3.0.0"

dependencies:
  http: ^1.1.0

dev_dependencies:
  very_good_analysis: ^5.1.0
